project:
  type: website
  output-dir: _site

website:
  title: "quarto-liveurl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: example.qmd
        text: Core Features
      - href: example-sticky.qmd
        text: Sticky & Global
      - href: example-paper.qmd
        text: Paper Summary
