project:
  type: website
  output-dir: _site

format:
  revealjs:
    footer: "[quarto-liveurl](https://parmsam.github.io/quarto-liveurl/)"

website:
  title: "quarto-liveurl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: example.qmd
        text: Core Features
      - href: example-sticky.qmd
        text: Sticky & Global
      - href: example-paper.qmd
        text: Paper Summary
      - href: example-chat.qmd
        text: Agenda Chat
    right:
      - icon: github
        href: https://github.com/parmsam/quarto-liveurl
        aria-label: GitHub
